/**
 * This class is generated by jOOQ
 */
package tech.codingclub.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MusicRecord extends org.jooq.impl.TableRecordImpl<tech.codingclub.tables.records.MusicRecord> implements org.jooq.Record9<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -2089534748;

	/**
	 * Setter for <code>public.music.singers</code>.
	 */
	public void setSingers(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.music.singers</code>.
	 */
	public java.lang.String getSingers() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>public.music.parent_link</code>.
	 */
	public void setParentLink(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.music.parent_link</code>.
	 */
	public java.lang.String getParentLink() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.music.album</code>.
	 */
	public void setAlbum(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.music.album</code>.
	 */
	public java.lang.String getAlbum() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.music.lyricist</code>.
	 */
	public void setLyricist(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.music.lyricist</code>.
	 */
	public java.lang.String getLyricist() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.music.music_director</code>.
	 */
	public void setMusicDirector(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.music.music_director</code>.
	 */
	public java.lang.String getMusicDirector() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>public.music.Duration</code>.
	 */
	public void setDuration(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.music.Duration</code>.
	 */
	public java.lang.String getDuration() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>public.music.Child_link</code>.
	 */
	public void setChildLink(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.music.Child_link</code>.
	 */
	public java.lang.String getChildLink() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>public.music.download_128</code>.
	 */
	public void setDownload_128(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.music.download_128</code>.
	 */
	public java.lang.String getDownload_128() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>public.music.download_256</code>.
	 */
	public void setDownload_256(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.music.download_256</code>.
	 */
	public java.lang.String getDownload_256() {
		return (java.lang.String) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return tech.codingclub.tables.Music.MUSIC.SINGERS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return tech.codingclub.tables.Music.MUSIC.PARENT_LINK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return tech.codingclub.tables.Music.MUSIC.ALBUM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return tech.codingclub.tables.Music.MUSIC.LYRICIST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return tech.codingclub.tables.Music.MUSIC.MUSIC_DIRECTOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return tech.codingclub.tables.Music.MUSIC.DURATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return tech.codingclub.tables.Music.MUSIC.CHILD_LINK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return tech.codingclub.tables.Music.MUSIC.DOWNLOAD_128;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return tech.codingclub.tables.Music.MUSIC.DOWNLOAD_256;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getSingers();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getParentLink();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getAlbum();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getLyricist();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getMusicDirector();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getDuration();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getChildLink();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getDownload_128();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getDownload_256();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MusicRecord value1(java.lang.String value) {
		setSingers(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MusicRecord value2(java.lang.String value) {
		setParentLink(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MusicRecord value3(java.lang.String value) {
		setAlbum(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MusicRecord value4(java.lang.String value) {
		setLyricist(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MusicRecord value5(java.lang.String value) {
		setMusicDirector(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MusicRecord value6(java.lang.String value) {
		setDuration(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MusicRecord value7(java.lang.String value) {
		setChildLink(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MusicRecord value8(java.lang.String value) {
		setDownload_128(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MusicRecord value9(java.lang.String value) {
		setDownload_256(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MusicRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.lang.String value7, java.lang.String value8, java.lang.String value9) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MusicRecord
	 */
	public MusicRecord() {
		super(tech.codingclub.tables.Music.MUSIC);
	}

	/**
	 * Create a detached, initialised MusicRecord
	 */
	public MusicRecord(java.lang.String singers, java.lang.String parentLink, java.lang.String album, java.lang.String lyricist, java.lang.String musicDirector, java.lang.String duration, java.lang.String childLink, java.lang.String download_128, java.lang.String download_256) {
		super(tech.codingclub.tables.Music.MUSIC);

		setValue(0, singers);
		setValue(1, parentLink);
		setValue(2, album);
		setValue(3, lyricist);
		setValue(4, musicDirector);
		setValue(5, duration);
		setValue(6, childLink);
		setValue(7, download_128);
		setValue(8, download_256);
	}
}
