/**
 * This class is generated by jOOQ
 */
package tech.codingclub;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in public
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.coders
	 */
	public static final tech.codingclub.tables.Coders CODERS = tech.codingclub.tables.Coders.CODERS;

	/**
	 * The table public.member
	 */
	public static final tech.codingclub.tables.Member MEMBER = tech.codingclub.tables.Member.MEMBER;

	/**
	 * The table public.music
	 */
	public static final tech.codingclub.tables.Music MUSIC = tech.codingclub.tables.Music.MUSIC;
}
